"""add id-connect

Revision ID: 54dcbe749322
Revises: dbfd138731a1
Create Date: 2026-02-06 17:53:45.821181

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "54dcbe749322"
down_revision: Union[str, Sequence[str], None] = "dbfd138731a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
