"""added ondelete Gallery, GeneratedPdf

Revision ID: 8172470ccc95
Revises: d5ed0e9bc0b8
Create Date: 2026-03-30 13:54:46.276022

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8172470ccc95"
down_revision: Union[str, Sequence[str], None] = "d5ed0e9bc0b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("gallery_manga_id_fkey"), "gallery", type_="foreignkey")
    op.create_foreign_key(
        None, "gallery", "mangas", ["manga_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("generated_pdf_id_manga_fkey"), "generated_pdf", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "generated_pdf", "mangas", ["id_manga"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "generated_pdf", type_="foreignkey")
    op.create_foreign_key(
        op.f("generated_pdf_id_manga_fkey"),
        "generated_pdf",
        "mangas",
        ["id_manga"],
        ["id"],
    )
    op.drop_constraint(None, "gallery", type_="foreignkey")
    op.create_foreign_key(
        op.f("gallery_manga_id_fkey"), "gallery", "mangas", ["manga_id"], ["id"]
    )
    # ### end Alembic commands ###
