"""add generated_pdf table and relationship

Revision ID: 9600b2f75493
Revises: 
Create Date: 2026-02-06 13:08:33.631494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9600b2f75493'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.Column('id_file', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_pdf_id_file', 'generated_pdf', ['id_file'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_generated_pdf_id_file', table_name='generated_pdf')
    op.drop_table('generated_pdf')
    # ### end Alembic commands ###
