"""removed model generated PDF beacause relic of the past

Revision ID: d3b30d69205c
Revises: 8172470ccc95
Create Date: 2026-04-08 21:28:48.631407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3b30d69205c"
down_revision: Union[str, Sequence[str], None] = "8172470ccc95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_generated_pdf_id_file"), table_name="generated_pdf")
    op.drop_table("generated_pdf")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_pdf",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("id_manga", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "id_file", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_manga"],
            ["mangas.id"],
            name=op.f("generated_pdf_id_manga_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("generated_pdf_pkey")),
        sa.UniqueConstraint(
            "id_manga",
            name=op.f("generated_pdf_id_manga_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_generated_pdf_id_file"), "generated_pdf", ["id_file"], unique=False
    )
    # ### end Alembic commands ###
