"""Added cascade deleted for Manga, Gallery, GeneratedPdf, and GenreManga

Revision ID: d5ed0e9bc0b8
Revises: 93f4dc2b989e
Create Date: 2026-03-30 13:33:47.097941

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d5ed0e9bc0b8"
down_revision: Union[str, Sequence[str], None] = "93f4dc2b989e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("genre_manga_manga_id_fkey"), "genre_manga", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("genre_manga_genre_id_fkey"), "genre_manga", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "genre_manga", "mangas", ["manga_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "genre_manga", "genres", ["genre_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "genre_manga", type_="foreignkey")
    op.drop_constraint(None, "genre_manga", type_="foreignkey")
    op.create_foreign_key(
        op.f("genre_manga_genre_id_fkey"), "genre_manga", "genres", ["genre_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("genre_manga_manga_id_fkey"), "genre_manga", "mangas", ["manga_id"], ["id"]
    )
    # ### end Alembic commands ###
