"""changed int to str

Revision ID: fe78d440fe73
Revises: 54dcbe749322
Create Date: 2026-02-06 18:26:31.541134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe78d440fe73"
down_revision: Union[str, Sequence[str], None] = "54dcbe749322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generated_pdf",
        "id_file",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generated_pdf",
        "id_file",
        existing_type=sa.String(length=256),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
